[package]
edition = "2024"
license.workspace = true
name = "xmtp_v2"
version.workspace = true

[dependencies]
aes-gcm = "0.10.3"
ecdsa = "0.16.9"
hex = { workspace = true }
hkdf.workspace = true
k256 = { version = "0.13.4", features = ["ecdh"] }
rand = { workspace = true }
sha2.workspace = true
sha3.workspace = true 

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js"] }
